version: '3.8'

services:
  tams-api:
    build: .
    ports:
      - "8000:8000"
    environment:
      - VAST_DATA_DIR=/app/vast_data
      - LOG_LEVEL=INFO
      - DEBUG=false
    volumes:
      - vast_data:/app/vast_data
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  vast_data:
    driver: local