apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: tams

resources:
- namespace.yaml
- secrets.yaml
- configmap.yaml
- service-account.yaml
- deployment.yaml
- service.yaml
- ingress.yaml
- hpa.yaml
- pdb.yaml
- network-policy.yaml

commonLabels:
  app: tams-api
  version: v1
  environment: production

images:
- name: tams-api
  newTag: latest 