apiVersion: v1
kind: ServiceAccount
metadata:
  name: tams-api-sa
  namespace: tams
  labels:
    app: tams-api
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: tams-api-role
  namespace: tams
rules:
- apiGroups: [""]
  resources: ["pods", "services", "endpoints"]
  verbs: ["get", "list", "watch"]
- apiGroups: [""]
  resources: ["events"]
  verbs: ["create", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: tams-api-rolebinding
  namespace: tams
subjects:
- kind: ServiceAccount
  name: tams-api-sa
  namespace: tams
roleRef:
  kind: Role
  name: tams-api-role
  apiGroup: rbac.authorization.k8s.io 